### ISSUE TITLE
Path name wrong in script

### ISSUE THREAD

**Issue by Sounak008** [darkk99/aseprite-resources#2]
The path name in the install.sh script is wrong. It should be aseprite-resources-main and not aseprite-resources.

Major issue, please fix

**Comment by carnivorecookies** [comment]
I'll probably be able to fix this around 4 or 5 PM EST since I'm busy before that time. I initially cloned the repo for maintaining with `git clone https://github.com/darkk99 -d ~/aseprite-resources` without thinking of it being cloned with --branch or being cloned into another directory. I'll try to implement a universal solution that works no matter where it was cloned into (*should* be possible with some regex)

**Comment by carnivorecookies** [comment]
should be fixed with the latest commit, with the side effect of needing to manually add the aseprite binary to $PATH (i find it intrusive for a script to modify system variables)
